#!/usr/bin/env python

import cloudscraper
from bs4 import BeautifulSoup
import sys


def get_app_info(app_name):
    scraper = cloudscraper.create_scraper()  # Create a cloudscraper instance

    # URL of the search page for the specified app_name
    search_url = f'https://apkpure.com/search?q={app_name.replace(" ", "+")}'

    try:
        response = scraper.get(search_url)  # Send a request to the search page
        response.raise_for_status()  # Check if the request was successful
    except Exception as e:
        print(f"Error: Unable to retrieve search results - {e}")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    # Find the first app link in the search results
    app_link = soup.find("a", {"class": "first-info"})["href"]

    if not app_link:
        print(f"Error: No results found for '{app_name}'.")
        return None

    try:
        response = scraper.get(app_link)  # Send a request to the app page
        response.raise_for_status()  # Check if the request was successful
    except Exception as e:
        print(f"Error: Unable to retrieve app information - {e}")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    # Extract the app name, download URL, and other relevant information
    app_name = soup.find("div", {"class": "title_link"}).find("h1").text.strip()
    download_url = soup.find("a", {"class": "download_apk_news"})["href"]
    version = soup.find("p", {"class": "details_sdk"}).find("span").text.strip()
    developer = soup.find("span", {"class": "developer"}).find("a").text.strip()

    app_info = {
        "App Name": app_name,
        "Package Name": download_url.split("/")[-2],
        "Download URL": "https://m.apkpure.com" + download_url,
        "Version": version,
        "Developer": developer,
    }

    return app_info


if __name__ == "__main__":
    if len(sys.argv) > 1:
        app_name = " ".join(
            sys.argv[1:]
        )  # Take the app_name from command-line arguments
    else:
        app_name = input("Enter the name of the app you want to search for: ")
        print()

    app_info = get_app_info(app_name)

    if app_info:
        for key, value in app_info.items():
            print(f"{key}: {value}")

# vim:ft=python
